name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run Tests
        run: tox

  deploy:
    runs-on: ubuntu-latest
    needs: [test] # Ensures deployment runs only after tests succeed
    if: github.ref == 'refs/heads/main' # Deploys only on the main branch
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn

      - name: Deploy Application
        run: |
          uvicorn web.main:app --host 0.0.0.0 --port 8000

 
